name: julep-llm-proxy

services:
  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    volumes:
      - ./litellm-config.yaml:/app/config.yaml
      - .keys:/app/.keys
    ports:
      - "4000:4000"
    env_file:
      - ../.env
    command:
      [
        "--config",
        "/app/config.yaml",
        "--port",
        "4000",
        "--num_workers",
        "8",
        "--telemetry",
        "False"
      ]

    depends_on:
      - litellm-db
      - litellm-redis

  litellm-db:
    image: postgres:16
    restart: always
    volumes:
      - litellm-db-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    
    # FIXME: This combination of env_file and environment is not working
    env_file:
      - ../.env
    environment:
      - POSTGRES_DB=${LITELLM_POSTGRES_DB}
      - POSTGRES_USER=${LITELLM_POSTGRES_USER}
      - POSTGRES_PASSWORD=${LITELLM_POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${LITELLM_POSTGRES_DB} -U ${LITELLM_POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10

  litellm-redis:
    image: redis/redis-stack-server
    restart: always
    volumes:
      - litellm-redis-data:/data
    ports:
      - "16379:6379"
    env_file:
      - ../.env

volumes:
  litellm-db-data:
  litellm-redis-data:
