name: julep-agents-api

services:
  agents-api:
    image: julepai/agents-api:${TAG:-dev}
    env_file:
      - ../.env
    container_name: agents-api
    depends_on:
      memory-store:
        condition: service_started
      worker:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    develop:
      watch:
        - action: sync+restart
          path: ./agents_api
          target: /app/agents_api
          ignore:
            - ./**/*.pyc
        - action: rebuild
          path: poetry.lock
        - action: rebuild
          path: Dockerfile

  worker:
    image: julepai/worker:${TAG:-dev}
    env_file:
      - ../.env

    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      text-embeddings-inference:
        condition: service_started
      temporal:
        condition: service_started

    develop:
      watch:
        - action: sync+restart
          path: ./agents_api
          target: /app/agents_api
          ignore:
            - ./**/*.pyc
        - action: rebuild
          path: poetry.lock
        - action: rebuild
          path: Dockerfile.worker

  text-embeddings-inference:
    container_name: text-embeddings-inference
    environment:
      - DTYPE=float16
      - MODEL_ID=Alibaba-NLP/gte-large-en-v1.5

    image: ghcr.io/huggingface/text-embeddings-inference:1.5
    ports:
      - "8082:80"
    volumes:
      - ~/.cache/huggingface/hub:/data
    shm_size: "2gb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


  cozo-migrate:
    image: julepai/cozo-migrate:${TAG:-dev}
    env_file:
      - ../.env

    container_name: cozo-migrate
    depends_on:
      memory-store:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile.migration
    restart: "no" # Make sure to double quote this

    develop:
      watch:
        - action: sync+restart
          path: ./migrations
          target: /app/migrations
        - action: rebuild
          path: Dockerfile.migration

volumes:
  temporal_data:
